version: '3.8'

services:
  app:
    image: node:latest
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8090:8090"
    command: sh -c 'npm install && npm start'
    restart: always