services:
  app:
    image: node:latest
    container_name: flowrite
    working_dir: /flowrite
    volumes:
      - .:/flowrite
    env_file:
      - .env
    ports:
      - "8003:8003"
    command: sh -c 'npm install && npm start'
    restart: always